apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstspring
  labels:
    app: firstspring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstspring
  template:
    metadata:
      labels:
        app: firstspring
    spec:
      containers:
      - name: firstspring
        image: mukhou/firstspring
        volumeMounts:
          # `name` here must match the name from the volumes section of this pod
          - name: firstvol
            mountPath: /etc/config/app.properties
            subPath: app.properties
      # Add the ConfigMap as a volume to the Pod
      volumes:
        # `name` here must match the name specified in the volume mount
        - name: firstvol
          configMap:
            # `name` here must match the name of the ConfigMap you want to use
            name: firstcm
