apiVersion: v1
kind: Service
metadata:
  name: firstspring
  labels:
    app: firstspring
spec:
  type: ClusterIP
  ports:
  - name: 8080-8080
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: firstspring
